# coverage 라는 yml 파일을 만들어서, 유닛테스트를 위한 테스트 파일이 통과 안되면 Merge가 안되게 만들기 + 리포트까지


name: Coverage Report

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9' 
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # 모든 *_test.py 파일(유닛 테스트)가 통과하면 merge 가 되도록 설정
      - name: Generate coverage report
        run: |
          coverage run --source=./ -m unittest discover -p "*_test.py"
          coverage xml
    