# Lint를 잘 따랐는지를 확인하고 CI 를 진행하기 위한 yml 파일입니다.

# 이름 명시
name: Lint Code Base

# 트리거
#[push, pull_request] 가능함
on: push

# Jobs 에는 어떤 Action(통과해야지 MERGE 할 수 있는)들을 해볼 것인지를 명시함,
jobs:
  # Job Key 설정 -> 여러가지 action들을 묶어서 하나의 job으로, job key를 이용해서 job에 접근
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    # job의 구체적인 환경 설정
    env:
      OS: ${{ matrix.os }}
      # Ubuntu의 파이썬 버전 명시
      PYTHON: '3.9'

    # github actions들을 명기
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
      # github에서 만든 checkout을 사용함
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Lint Code Base
      # github에서 만든 lint 모듈
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true


    mypy:
      name : mypy-check
      runs-on: ubuntu-latest
      steps:
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
            architecture: x64
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install mypy
          run: pip install mypy
        - name: Run mypy
          uses: sasanquaneuf/mypy-github-action@releases/v1
          with:
            checkName: 'mypy'   # NOTE: this needs to be the same as the job name
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}